version: '3.1'

services:
  auth-service:
    depends_on: 
      - mongo
    container_name: auth-service
    build: .
    ports:
      - 3000:3000

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: auth
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports: 
      - 27017:27017